library(tidyverse)
library(ggpubr)

#load data
usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

viability_table <- read.csv2("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/viability_table.csv")

load("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/patmeta_210324.RData")

#load table with disease entities  
diseases <- usedSamples_all |> 
  arrange(patientID) |> 
  dplyr::select (patientID, diagnosis) 
diseases

# merge the tables
merged_table <- cbind(diseases, viability_table) |> 
  relocate(diagnosis, .before = X10058.F4_1)
merged_table

#transfrom in long data frame
merged_table_long <- merged_table |>
  pivot_longer(cols = c(4:318), names_to = "drug", values_to = "viability")
merged_table_long

#remove last two characters from each string in 'drug' column
merged_table_long$drug <- str_sub(merged_table_long$drug, end = -3)
merged_table_long

#change order according to mean viability  
merged_table_conc <- merged_table_long |> 
  mutate(conc = rep(seq(1:5), times = nrow(merged_table_long)/5))

#focus on main diseases
merged_filtered <- merged_table_conc |>
  filter(str_detect(diagnosis, "CLL"))
  
#merge with patMeta
merged_filtered <- merged_filtered |> 
  group_by(drug, patientID)

df <- merge(merged_filtered, patMeta, by.x="patientID", by.y = "Patient.ID") 

#focus on BCR
df_bcr <- df |>
  filter(drug == "Ibrutinib" | drug == "Idelalisib")
  
df_bcr$conc <- replace(df_bcr$conc, df_bcr$conc %in% c(1,2,3,4,5), c("2","0.4","0.08","0.016","0.0032"))

df_bcr <- df_bcr  |> 
  filter(IGHV.status == "U")

df_bcr <- df_bcr[!(is.na(df_bcr$DDX3X)), ]  

#prepare table for bipartite plot
tst <- df_bcr |> 
  pivot_wider(names_from = "drug", values_from = "viability")
  

#plot graph
my_comparisons <- list(c("Ibrutinib", "Idelalisib"))

mycolors <- c("#E78AC3", "grey60")
names(mycolors) <- c(1,0)

theme_set(theme_classic() + theme(
panel.grid.major = element_blank(),
panel.grid.minor = element_blank(),
axis.text.x = element_text(color="black", size=8), 
axis.text.y = element_text(color="black", size=8), 
axis.title = element_text(size=8),
legend.title = element_text(size=8, face="bold"), legend.text=element_text(size=8), 
legend.key.size = unit(0.5, 'cm'),
#axis.line = element_line(size = 0.5)
))

p1 <- tst |> 
    mutate(`Ibrutinib (BTK)` = Ibrutinib, 
    `Idelalisib (PI3K)` = Idelalisib) |> 
    ggplot(aes(x=`Idelalisib (PI3K)`, y=`Ibrutinib (BTK)`, color=DDX3X)) + 
    geom_point(alpha = 0.75) + 
    geom_abline(slope=1, linetype="dashed")+
    scale_color_manual(values=mycolors, labels=c("unmutated", "mutated"))+
    theme_bw() +
    theme(strip.text.y = element_text(size = 0), 
        strip.text.x = element_text(size=8),
        axis.text.y = element_text(size =8, color="black"),
        axis.text.x = element_text(size =8, color="black"), 
        axis.title = element_text(size =8, color="black"),
        panel.spacing = unit(0.15, "lines"), 
        legend.title = element_text(size=8, face="bold"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", linewidth = 1, fill = NA),
        strip.background = element_rect(color = "black", linewidth = 1, fill = "grey90"),        
    plot.title = element_text(hjust=0.5, size=8, face="bold"), 
    legend.key.size = unit(0.5, 'cm'))+
    scale_y_continuous(breaks=seq(0.4,1.0, 0.2), limits=c(0.3,1.1)) +
    scale_x_continuous(breaks=seq(0.4,1.0, 0.2), limits=c(0.3,1.1)) +
    guides(color = guide_legend(override.aes = list(label = ""))) +
    facet_wrap(~conc, ncol=5)+
    labs(title=expression(bold(paste("Concentration (", mu, "M)"))), 
    x="Idelalisib (PI3K)", y= "Ibrutinib (BTK)")
  p1  

SFig11b <- p1 + theme(plot.margin = margin(l = 1, r = 1, t=1, b=1.5, unit = "cm"))
SFig11b