library(tidyverse)
library(dplyr)
library(plotrix)
library(drc)
library(scales)

#load data
usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

viability_table <- read.csv2("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/viability_table.csv")

#load table with disease entities  
diseases <- usedSamples_all |> 
  arrange(patientID) |> 
    dplyr::select(patientID, diagnosis) 

# merge the tables
merged_table <- cbind(diseases, viability_table) |> 
  relocate(diagnosis, .before = X10058.F4_1)
merged_table

#transfrom in long data frame
merged_table_long <- merged_table |>
  pivot_longer(cols = c(4:318), names_to = "drug", values_to = "viability")
merged_table_long

#focus on main diseases
merged_filtered <- merged_table_long
#|>filter(str_detect(diagnosis, "CLL") | str_detect(diagnosis, "MCL") |         str_detect(diagnosis, "AML") | str_detect(diagnosis, "B-ALL") | str_detect(diagnosis, "T-ALL") | str_detect(diagnosis, "B-PLL")  | str_detect(diagnosis, "T-PLL"))
merged_filtered 

#remove last two characters from each string in 'drug' column
merged_filtered<- merged_filtered |> 
  mutate(drug_sub = str_sub(merged_filtered$drug, end = -3)) |> 
    filter(diagnosis != "")

#select venetoclax and diseases
merged_filtered <- merged_filtered |> 
    filter(drug_sub == "Venetoclax") |> 
    filter(diagnosis == "AML" | diagnosis == "B-ALL" | diagnosis == "Sezary" | diagnosis == "CLL" | diagnosis == "T-ALL" | diagnosis == "MCL") |> 
    mutate(drug = fct_recode(drug, "0.00064" = "Venetoclax_5",
"0.0032" = "Venetoclax_4", "0.016" = "Venetoclax_3", "0.08" = "Venetoclax_2", "0.4" = "Venetoclax_1"))

#make concentrations numeric
merged_filtered$drug <- as.numeric(as.character(merged_filtered$drug))

#calculate medians for each disease
merged_median <- merged_filtered |> 
  group_by(diagnosis, drug) |> summarize(med=median(viability))

merged_median_cll <- merged_median |> 
  filter(diagnosis == "CLL")
merged_median_aml <- merged_median |> 
  filter(diagnosis == "AML")
merged_median_ball <- merged_median |> 
  filter(diagnosis == "B-ALL")
merged_median_tall <- merged_median |> 
  filter(diagnosis == "T-ALL")
merged_median_mcl <- merged_median |> 
  filter(diagnosis == "MCL")  
merged_median_sez <- merged_median |> 
  filter(diagnosis == "Sezary")

# Fit the dose-response model
#CLL
model_cll <- drm(med ~ drug, data = merged_median_cll, fct = LL.4(names = c("hill", "min_value", "max_value", "ec_50")))
#AML
model_aml <- drm(med ~ drug, data = merged_median_aml, fct = LL.4(names = c("hill", "min_value", "max_value", "ec_50")))
#B-ALL
model_ball <- drm(med ~ drug, data = merged_median_ball, fct = LL.4(names = c("hill", "min_value", "max_value", "ec_50")))
#T-ALL
model_tall <- drm(med ~ drug, data = merged_median_tall, fct = LL.4(names = c("hill", "min_value", "max_value", "ec_50")))
#MCL
model_mcl <- drm(med ~ drug, data = merged_median_mcl, fct = LL.4(names = c("hill", "min_value", "max_value", "ec_50")))
#Sezary
model_sez <- drm(med ~ drug, data = merged_median_sez, fct = LL.4(names = c("hill", "min_value", "max_value", "ec_50")))

# Create a new data frame for prediction
#CLL
new_data_cll <- data.frame(drug = seq(min(merged_median_cll$drug), max(merged_median_cll$drug), length.out = 500))
new_data_cll$pred <- predict(model_cll, newdata = new_data_cll)
#AML
new_data_aml <- data.frame(drug = seq(min(merged_median_aml$drug), max(merged_median_aml$drug), length.out = 500))
new_data_aml$pred <- predict(model_aml, newdata = new_data_aml)
#B-ALL
new_data_ball <- data.frame(drug = seq(min(merged_median_ball$drug), max(merged_median_ball$drug), length.out = 500))
new_data_ball$pred <- predict(model_ball, newdata = new_data_ball)
#T-ALL
new_data_tall <- data.frame(drug = seq(min(merged_median_tall$drug), max(merged_median_tall$drug), length.out = 500))
new_data_tall$pred <- predict(model_tall, newdata = new_data_tall)
#MCL
new_data_mcl <- data.frame(drug = seq(min(merged_median_mcl$drug), max(merged_median_mcl$drug), length.out = 500))
new_data_mcl$pred <- predict(model_mcl, newdata = new_data_mcl)
#Sezary
new_data_sez <- data.frame(drug = seq(min(merged_median_sez$drug), max(merged_median_sez$drug), length.out = 500))
new_data_sez$pred <- predict(model_sez, newdata = new_data_sez)

# Add diagnosis column to each prediction dataframe
new_data_cll$diagnosis <- "CLL"
new_data_ball$diagnosis <- "B-ALL"
new_data_sez$diagnosis <- "Sezary"
new_data_aml$diagnosis <- "AML"
new_data_tall$diagnosis <- "T-ALL"
new_data_mcl$diagnosis <- "MCL"

all_predictions <- rbind(new_data_cll, new_data_ball, new_data_sez, new_data_aml, new_data_tall, new_data_mcl)

#add ic50
#CLL
coefs_cll <- setNames(model_cll$coefficients, c("hill", "min_value", "max_value", "ec_50"))
ic_50_cll <- with(as.list(coefs_cll),exp(log(ec_50) + (1 / hill) * log(max_value / (max_value - 2 * min_value))))
#AML
coefs_aml <- setNames(model_aml$coefficients, c("hill", "min_value", "max_value", "ec_50"))
ic_50_aml <- with(as.list(coefs_aml),exp(log(ec_50) + (1 / hill) * log(max_value / (max_value - 2 * min_value))))
#B-ALL
coefs_ball <- setNames(model_ball$coefficients, c("hill", "min_value", "max_value", "ec_50"))
ic_50_ball <- with(as.list(coefs_ball),exp(log(ec_50) + (1 / hill) * log(max_value / (max_value - 2 * min_value))))
#T-ALL
coefs_tall <- setNames(model_tall$coefficients, c("hill", "min_value", "max_value", "ec_50"))
ic_50_tall <- with(as.list(coefs_tall),exp(log(ec_50) + (1 / hill) * log(max_value / (max_value - 2 * min_value))))
#MCL
coefs_mcl <- setNames(model_mcl$coefficients, c("hill", "min_value", "max_value", "ec_50"))
ic_50_mcl <- with(as.list(coefs_mcl),exp(log(ec_50) + (1 / hill) * log(max_value / (max_value - 2 * min_value))))
#Sezary
coefs_sez <- setNames(model_sez$coefficients, c("hill", "min_value", "max_value", "ec_50"))
ic_50_sez <- with(as.list(coefs_sez),exp(log(ec_50) + (1 / hill) * log(max_value / (max_value - 2 * min_value))))

all_ic50 <- as.data.frame(cbind(rbind(ic_50_cll, ic_50_ball, ic_50_aml, ic_50_tall, ic_50_mcl), c("CLL", "B-ALL", "AML", "T-ALL", "MCL")))
all_ic50 <- data.frame(
  ic50 = as.numeric(all_ic50$V1),
  diagnosis = all_ic50$V2)
  
#set colors
mycolors <- setNames(c("#1F78B4", "#B2DF8A", "#A6CEE3", "darkgrey", "#E31A1C", "#FB9A99", "#FF7F00", "#CAB2D6"), c("MCL", "CLL", "T-PLL", "Sezary", "AML", "T-ALL", "B-ALL", "B-PLL"))  

#change order
# Add the diag factor to all_predictions with the same levels
all_predictions$diag <- factor(all_predictions$diagnosis, 
                              levels = c("CLL", "B-ALL", "MCL", "AML", "T-ALL", "Sezary"))

# Update the geom_line to use diag instead of diagnosis
geom_line(data = all_predictions, aes(x = drug, y = pred, color = diag))

# Do the same for all_ic50
all_ic50$diag <- factor(all_ic50$diagnosis, 
                       levels = c("CLL", "B-ALL", "MCL", "AML", "T-ALL", "Sezary"))

#plot
Fig3f <- merged_filtered |> 
  mutate(diag = factor(diagnosis, levels = c("CLL", "B-ALL", "MCL", "AML", "T-ALL", "Sezary"))) |> 
  ggplot(aes(x=drug, y=viability, group=diag, color=diag)) +
    geom_boxplot(aes(group=drug), alpha = 1, outlier.shape = NA) +
    geom_jitter(aes(group=diag), size=1, alpha = 0.25) +
    labs(title="Venetoclax (BCL2)", x=bquote("Concentration ("*mu*"M)"), y = "Viability") +
    theme_bw() +
    geom_line(data = all_predictions, aes(x = drug, y = pred, color = diagnosis))+
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x), labels = trans_format("log10", math_format(10^.x)))+
    facet_wrap(~diag, ncol=6) +
    geom_vline(data = all_ic50, aes(xintercept = ic50), 
               linetype = "dashed", color = "black", size = 0.4) +
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1)) +
    scale_color_manual(values=mycolors) +
    theme(legend.position = "none", 
          axis.text.x = element_text(angle = 0, color="black", size=8), 
          panel.grid = element_line(colour = "white"), 
          axis.text.y = element_text(color="black", size=8), 
          axis.title.y = element_text(size=8), 
          axis.title.x = element_text(size=8), 
          panel.border = element_rect(color = "black", linewidth = 1, fill = NA),
          strip.background = element_rect(color = "black", linewidth = 1, fill = "grey90"),
          plot.title = element_text(hjust=0.5, size=8, face="bold"), 
          strip.text = element_text(size = 8), 
          plot.margin = margin(l = 0.5, r = 1, unit = "cm"))
Fig3f