library(tidyverse)
library(plotrix)

#load data
usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

viability_table <- read.csv2("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/viability_table.csv")

#load table with disease entities  
diseases <- usedSamples_all |> 
  arrange(patientID) |> 
  dplyr::select (patientID, diagnosis) 
diseases

# merge the tables
merged_table <- cbind(diseases, viability_table) |> 
  relocate(diagnosis, .before = X10058.F4_1)
merged_table

#transfrom in long data frame
merged_table_long <- merged_table |>
  pivot_longer(cols = c(4:318), names_to = "drug", values_to = "viability")
merged_table_long

#focus on main diseases
merged_filtered <- merged_table_long |>
  filter(str_detect(diagnosis, "CLL") | str_detect(diagnosis, "MCL") |         str_detect(diagnosis, "AML") | str_detect(diagnosis, "B-ALL") |            str_detect(diagnosis, "T-ALL") | str_detect(diagnosis, "B-PLL")  |         str_detect(diagnosis, "T-PLL"))
merged_filtered 

#filter drugs of interest: PF.3758309
df_pf <- merged_filtered |>
  filter(str_detect(drug, "PF.3758309_1") | str_detect(drug, "PF.3758309_2") | str_detect(drug, "PF.3758309_3") | str_detect(drug, "PF.3758309_4") | str_detect(drug, "PF.3758309_5"))
df_pf

#create stats
pf_stat <- df_pf |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
pf_stat

#rename to concentrations
pf_conc <- pf_stat |>
  mutate(concentration = case_when(
  drug == "PF.3758309_1" ~ "2", 
  drug == "PF.3758309_2" ~ "0.4", 
  drug == "PF.3758309_3" ~ "0.08", 
  drug == "PF.3758309_4" ~ "0.016", 
  drug == "PF.3758309_5" ~ "0.0032"))

#plot
pf <- pf_conc |> 
  ggplot(aes(x=concentration, y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="PF-3758309 (PAK)",x="concentration [uM]", y = "viability")+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1))+
    theme_bw()
pf

#filter drugs of interest: OTX015
df_otx <- merged_filtered |>
  filter(str_detect(drug, "OTX015_1") | str_detect(drug, "OTX015_2") | str_detect(drug, "OTX015_3") | str_detect(drug, "OTX015_4") | str_detect(drug, "OTX015_5"))
df_otx

#create stats
otx_stat <- df_otx |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
otx_stat

#rename to concentrations
otx_conc <- otx_stat |>
  mutate(concentration = case_when(
  drug == "OTX015_5" ~ 0.016, 
  drug == "OTX015_4" ~ 0.08, 
  drug == "OTX015_3" ~ 0.4, 
  drug == "OTX015_2" ~ 2, 
  drug == "OTX015_1" ~ 10))

#plot
otx <- otx_conc |>
    ggplot(aes(x=factor(concentration), y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="OTX015 (BET)",x="concentration [uM]", y = "viability")+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1))+
    theme_bw()
otx

#filter drugs of interest: AZD8055
df_azd <- merged_filtered |>
  filter(str_detect(drug, "AZD8055_1") | str_detect(drug, "AZD8055_2") | str_detect(drug, "AZD8055_3") | str_detect(drug, "AZD8055_4") | str_detect(drug, "AZD8055_5"))
df_azd

#create stats
azd_stat <- df_azd |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
azd_stat

#rename to concentrations
azd_conc <- azd_stat |>
  mutate(concentration = case_when(
  drug == "AZD8055_1" ~ "2", 
  drug == "AZD8055_2" ~ "0.4", 
  drug == "AZD8055_3" ~ "0.08", 
  drug == "AZD8055_4" ~ "0.016", 
  drug == "AZD8055_5" ~ "0.0032"))

#plot
azd <- azd_conc |> 
  ggplot(aes(x=concentration, y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="AZD8055 (mTOR)",x="concentration [uM]", y = "viability")+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1))+
    theme_bw()
azd

#filter drugs of interest: Cytarabine
df_cyt <- merged_filtered |>
  filter(str_detect(drug, "Cytarabine_1") | str_detect(drug, "Cytarabine_2") | str_detect(drug, "Cytarabine_3") | str_detect(drug, "Cytarabine_4") | str_detect(drug, "Cytarabine_5"))
df_cyt

#create stats
cyt_stat <- df_cyt |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
cyt_stat

#rename to concentrations
cyt_conc <- cyt_stat |>
  mutate(concentration = case_when(
  drug == "Cytarabine_1" ~ 10, 
  drug == "Cytarabine_2" ~ 2, 
  drug == "Cytarabine_3" ~ 0.4, 
  drug == "Cytarabine_4" ~ 0.08, 
  drug == "Cytarabine_5" ~ 0.016))

#plot
cyt <- cyt_conc |> 
  ggplot(aes(x=factor(concentration), y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="Cytarabine",x="concentration [uM]", y = "viability")+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1))+
    theme_bw()
cyt

#filter drugs of interest: AZD6738
df_azd6 <- merged_filtered |>
  filter(str_detect(drug, "AZD6738_1") | str_detect(drug, "AZD6738_2") | str_detect(drug, "AZD6738_3") | str_detect(drug, "AZD6738_4") | str_detect(drug, "AZD6738_5"))
df_azd6

#create stats
azd6_stat <- df_azd6 |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
azd6_stat

#rename to concentrations
azd6_conc <- azd6_stat |>
  mutate(concentration = case_when(
  drug == "AZD6738_1" ~ 2, 
  drug == "AZD6738_2" ~ 0.4, 
  drug == "AZD6738_3" ~ 0.08, 
  drug == "AZD6738_4" ~ 0.016, 
  drug == "AZD6738_5" ~ 0.0032))

#plot
azd6 <- azd6_conc |> 
  ggplot(aes(x=factor(concentration), y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="AZD6738 (AKT)",x="concentration [uM]", y = "viability")+
    theme_bw()
azd6    

#filter drugs of interest: Nutlin-3a
df_nut <- merged_filtered |>
  filter(str_detect(drug, "Nutlin.3a_1") | str_detect(drug, "Nutlin.3a_2") | str_detect(drug, "Nutlin.3a_3") | str_detect(drug, "Nutlin.3a_4") | str_detect(drug, "Nutlin.3a_5"))
df_nut

#create stats
nut_stat <- df_nut |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
nut_stat

#rename to concentrations
nut_conc <- nut_stat |>
  mutate(concentration = case_when(
  drug == "Nutlin.3a_1" ~ 10, 
  drug == "Nutlin.3a_2" ~ 2, 
  drug == "Nutlin.3a_3" ~ 0.4, 
  drug == "Nutlin.3a_4" ~ 0.08, 
  drug == "Nutlin.3a_5" ~ 0.016))

#plot
nut <- nut_conc |> 
  ggplot(aes(x=factor(concentration), y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="Nutlin-3a (MDM2)",x="concentration [uM]", y = "viability")+
    theme_bw()
nut

#filter drugs of interest: Venetoclax
df_ven <- merged_filtered |>
  filter(str_detect(drug, "Venetoclax_1") | str_detect(drug, "Venetoclax_2") | str_detect(drug, "Venetoclax_3") | str_detect(drug, "Venetoclax_4") | str_detect(drug, "Venetoclax_5"))
df_ven

#create stats
ven_stat <- df_ven |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
ven_stat

#rename to concentrations
ven_conc <- ven_stat |>
  mutate(concentration = case_when(
  drug == "Venetoclax_1" ~ 0.4, 
  drug == "Venetoclax_2" ~ 0.08, 
  drug == "Venetoclax_3" ~ 0.016, 
  drug == "Venetoclax_4" ~ 0.0032, 
  drug == "Venetoclax_5" ~ 0.00064))

#plot
ven <- ven_conc |> 
  ggplot(aes(x=factor(concentration), y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="Venetoclax (BCL2)",x="concentration [uM]", y = "viability")+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1))+
    theme_bw()
ven

#filter drugs of interest: Duvelisib
df_duv <- merged_filtered |>
  filter(str_detect(drug, "Duvelisib_1") | str_detect(drug, "Duvelisib_2") | str_detect(drug, "Duvelisib_3") | str_detect(drug, "Duvelisib_4") | str_detect(drug, "Duvelisib_5"))
df_duv

#create stats
duv_stat <- df_duv |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
duv_stat

#rename to concentrations
duv_conc <- duv_stat |>
  mutate(concentration = case_when(
  drug == "Duvelisib_1" ~ 2, 
  drug == "Duvelisib_2" ~ 0.4, 
  drug == "Duvelisib_3" ~ 0.08, 
  drug == "Duvelisib_4" ~ 0.016, 
  drug == "Duvelisib_5" ~ 0.0032))

#plot
duv <- duv_conc |> 
  ggplot(aes(x=factor(concentration), y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="Duvelisib (PI3Kγ/δ)",x="concentration [uM]", y = "viability")+
    theme_bw()
duv

#filter drugs of interest: Ibrutinib
df_ibr <- merged_filtered |>
  filter(str_detect(drug, "Ibrutinib_1") | str_detect(drug, "Ibrutinib_2") | str_detect(drug, "Ibrutinib_3") | str_detect(drug, "Ibrutinib_4") | str_detect(drug, "Ibrutinib_5"))
df_duv

#create stats
ibr_stat <- df_ibr |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
ibr_stat

#rename to concentrations
ibr_conc <- ibr_stat |>
  mutate(concentration = case_when(
  drug == "Ibrutinib_1" ~ 10, 
  drug == "Ibrutinib_2" ~ 2, 
  drug == "Ibrutinib_3" ~ 0.4, 
  drug == "Ibrutinib_4" ~ 0.08, 
  drug == "Ibrutinib_5" ~ 0.016))

#plot
ibr <- ibr_conc |> 
  ggplot(aes(x=factor(concentration), y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="Ibrutinib (BTK)",x="concentration [uM]", y = "viability")+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1))+
    theme_bw()
ibr

#filter drugs of interest: MK-2206
df_mk <- merged_filtered |>
  filter(str_detect(drug, "MK.2206_1") | str_detect(drug, "MK.2206_2") | str_detect(drug, "MK.2206_3") | str_detect(drug, "MK.2206_4") | str_detect(drug, "MK.2206_5"))
df_mk

#create stats
mk_stat <- df_mk |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
mk_stat

#rename to concentrations
mk_conc <- mk_stat |>
  mutate(concentration = case_when(
  drug == "MK.2206_1" ~ 2, 
  drug == "MK.2206_2" ~ 0.4, 
  drug == "MK.2206_3" ~ 0.08, 
  drug == "MK.2206_4" ~ 0.016, 
  drug == "MK.2206_5" ~ 0.0032))

#plot
mk <- mk_conc |> 
  ggplot(aes(x=factor(concentration), y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="MK-2206 (AKT)",x="concentration [uM]", y = "viability")+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1))+
    theme_bw()
mk

#filter drugs of interest: Panobinostat
df_pan <- merged_filtered |>
  filter(str_detect(drug, "Panobinostat_1") | str_detect(drug, "Panobinostat_2") | str_detect(drug, "Panobinostat_3") | str_detect(drug, "Panobinostat_4") | str_detect(drug, "Panobinostat_5"))
df_pan

#create stats
pan_stat <- df_pan |>   
    group_by(drug, diagnosis) |>
    summarize(mean=mean(viability), 
    std.error=std.error(viability))
pan_stat

#rename to concentrations
pan_conc <- pan_stat |>
  mutate(concentration = case_when(
  drug == "Panobinostat_1" ~ 0.4, 
  drug == "Panobinostat_2" ~ 0.08, 
  drug == "Panobinostat_3" ~ 0.016, 
  drug == "Panobinostat_4" ~ 0.0032, 
  drug == "Panobinostat_5" ~ 0.00064))

#plot
pan <- pan_conc |> 
  ggplot(aes(x=factor(concentration), y=mean, group=diagnosis, color=diagnosis)) +
    geom_errorbar(aes(ymin=mean-std.error, ymax=mean+std.error), width=.5, position=position_dodge(0.01))+
    geom_line(aes(group=diagnosis))+
    labs(title="Panobinostat (HDAC)",x="concentration [uM]", y = "viability")+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1))+
    theme_bw()
pan


#combined plot: load package
library(cowplot)
library(patchwork)
p <- ggdraw() +
  draw_plot(ven, x = 0, y = 0, width = 0.5, height = .25) +
  draw_plot(duv, x = 0.5, y = 0, width = 0.5, height = .25) +
  draw_plot(azd6, x = 0, y = 0.25, width = 0.5, height = .25) +
  draw_plot(nut, x = 0.5, y = 0.25, width = 0.5, height = .25) +
  draw_plot(azd, x = 0, y = 0.5, width = 0.5, height = .25) +
  draw_plot(cyt, x = 0.5, y = 0.5, width = 0.5, height = .25) +
  draw_plot(pf, x = 0, y = 0.75, width = 0.5, height = .25) +
  draw_plot(otx, x = 0.5, y = 0.75, width = 0.5, height = .25) 
p  

#adjust aesthetics for pf, ibr, azd
mycolors <- setNames(c("#1F78B4", "#B2DF8A", "#A6CEE3", "grey", "#E31A1C", "#FB9A99", "#FF7F00", "#CAB2D6"), c("MCL", "CLL", "T-PLL", "other", "AML", "T-ALL", "B-ALL", "B-PLL"))

ibr <- ibr + theme_classic()+labs(y="Viability", x=bquote("Concentration ("*mu*"M)"), color="Diagnosis")+
theme(axis.text.x = element_text(angle=45, hjust =1,color="black", size=8), axis.text.y = element_text(color="black", size=8), legend.title = element_text(size=8), legend.text=element_text(size=8), axis.line = element_line(linewidth = 0.5), axis.title = element_text(size=8), plot.title = element_text(hjust=0.5, size=8, face="bold"))+scale_color_manual(values=mycolors)

pf <- pf + theme_classic()+labs(y="Viability", x=bquote("Concentration ("*mu*"M)"), color="Diagnosis")+
theme(axis.text.x = element_text(angle=45, hjust =1, color="black", size=8), axis.text.y = element_text(color="black", size=8), legend.title = element_text(size=8), legend.text=element_text(size=8), axis.line = element_line(linewidth = 0.5), axis.title = element_text(size=8), plot.title = element_text(hjust=0.5, size=8, face="bold"))+scale_color_manual(values=mycolors)

azd <- azd + theme_classic()+labs(y="Viability", x=bquote("Concentration ("*mu*"M)"), color="Diagnosis")+
theme(axis.text.x = element_text(angle=45, hjust =1, color="black", size=8), axis.text.y = element_text(color="black", size=8), legend.title = element_text(size=8), legend.text=element_text(size=8), axis.line = element_line(linewidth = 0.5), axis.title = element_text(size=8), plot.title = element_text(hjust=0.5, size=8, face="bold"))+scale_color_manual(values=mycolors)

Fig3e <- ibr+pf+azd + plot_layout(ncol=3, guides =
'collect') & theme(legend.position='right', legend.title= element_text(size=8, face="bold"), plot.margin = margin(t=0.25, l=0.5, b=0.25, r=0.5, unit = "cm")) &
  guides(
    color = guide_legend(ncol = 1),
    fill = guide_legend(ncol = 1),
    shape = guide_legend(ncol = 1),
    linetype = guide_legend(ncol = 1)
  )
Fig3e

                  
