# Load required libraries
library(ComplexHeatmap)
library(circlize)
library(grid)
library(tidyverse)
library(dplyr)
library(RColorBrewer)
library(ggplotify)

load("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/patmeta_210324.RData")

usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

merged <- merge(usedSamples_all, patMeta, by.x="patientID", by.y="Patient.ID") |> filter(diagnosis.x == "CLL")
  
load("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/survival_190516.RData")

# Prepare the genetic alteration data
#exclude genetic aberrations without hits
oncoprint_data <- merged
#[,12:136] 

#remove del5IgH
oncoprint_data <- oncoprint_data |> 
  dplyr::select(!del5IgH)

# Remove the first two columns (IGHV.status and Methylation_Cluster)
matrix_data <- as.matrix(oncoprint_data[, -c(1:13)])
rownames(matrix_data) <- merged$patientID 
genetic_variations <- t(matrix_data)

#exclude aberrations with less than 8 events
genetic_variations <- data.matrix(genetic_variations)

genetic_variations_num <- matrix(as.numeric(genetic_variations), ncol = 275)
rownames(genetic_variations_num) <- rownames(genetic_variations)
colnames(genetic_variations_num) <- colnames(genetic_variations)

genetic_variations_num <- as.data.frame(genetic_variations_num)
genetic_variations_num$count <- rowSums(!(is.na(genetic_variations_num) | genetic_variations_num == 0)) 

genetic_variations_num <- genetic_variations_num |> 
  filter(count >7)
  

#re-adjust matrix für heatmap
genetic_variations_num[genetic_variations_num==0]<-""
genetic_variations_num[is.na(genetic_variations_num)]<-""

genetic_variations_red <- dplyr::select(genetic_variations_num, !count)
genetic_variations_red <- as.matrix(genetic_variations_red)

#annotations
#annotation for IGHV status
ighv_anno <- oncoprint_data[,12]
ighv_anno <- ighv_anno %>% replace(is.na(.), "unknown")
ighv_colors <- colorRampPalette(brewer.pal(9, "Set1"))(length(unique(ighv_anno)))
annotation_colors <- setNames(ighv_colors, unique(ighv_anno))

#annotation for Methylation
meth_anno <- oncoprint_data[,13]
meth_anno <- factor(meth_anno, levels = c("HP", "IP","LP", "unknown"))
meth_anno <- meth_anno %>% replace(is.na(.), "unknown")
meth_colors <- colorRampPalette(brewer.pal(8, "Set2"))(length(unique(meth_anno)))
annotation_colors_meth <- setNames(meth_colors, unique(meth_anno))

#annotation for center
center_anno <- oncoprint_data[,8]
center_anno <- factor(center_anno, levels = c("HD", "HD-DNA", "H68", "MIR34a", "FB", "NOV", "MDACC", "MUN", "HCL_HD_Andrulis", "OX", "BARC", "ZCH_2"))
center_colors <- colorRampPalette(brewer.pal(3, "Paired"))(length(unique(center_anno)))

#change center label
center_anno <- fct_recode(center_anno,
"Zürich" = "ZCH_2",
"Barcelona" = "BARC",
"Heidelberg" = "HD")

annotation_colors_center <- setNames(center_colors, unique(center_anno))

#change IGHV label
ighv_anno <- fct_recode(ighv_anno,
"mutated" = "M",
"unmutated" = "U")

annotation_colors <- setNames(ighv_colors, unique(ighv_anno))

#annotation for prior treatment
#prior_tx <- merge(treatmentTab, oncoprint_data, by = "sampleID") |> 
#tx_anno <- prior_tx$treatStatus
#tx_anno[tx_anno == "treatedBefore" | tx_anno == "inChemo" | tx_anno == "inTargeted"] <- "Treated"
#tx_anno[tx_anno == "untreated" | tx_anno == "unclear" | is.na(tx_anno)] <- "Untreated"
#tx_anno <- factor(tx_anno, levels = c("Treated", "Untreated"))
#annotation_colors_tx <- setNames(c("black", "white"), c("Treated", "Untreated"))

ha <- HeatmapAnnotation(Center = center_anno, IGHV = ighv_anno, Methylation = meth_anno, annotation_name_gp = gpar(fontsize = 8), col = list(Center =  annotation_colors_center, IGHV = annotation_colors, Methylation = annotation_colors_meth), annotation_legend_param = list(
    Center = list(
      title_gp = gpar(fontsize = 8, fontface = "bold"),
      labels_gp = gpar(fontsize = 8)
    ),
    IGHV = list(
      title_gp = gpar(fontsize = 8, fontface = "bold"),
      labels_gp = gpar(fontsize = 8)
    ),
    Methylation = list(
      title_gp = gpar(fontsize = 8, fontface = "bold"),
      labels_gp = gpar(fontsize = 8)
    )))

heatmap_legend_param = list(title="Alteration", at = c("1"), title_gp = gpar(fontsize = 8),  # Legend title font size
  labels_gp = gpar(fontsize = 8))

# Create the oncoprint
  oncoprint <- oncoPrint(
    genetic_variations_red,
    alter_fun = list(
      background = function(x, y, w, h) {
        grid.rect(x, y, w, h, gp = gpar(fill = "#F8F8F8", col = "white"))
      },
      "1" = function(x, y, w, h) grid.rect(x, y, w, h, gp = gpar(fill = "black", col = "white")), col = "white"),
    col = c("1" = "black"), na_col = "white",
    remove_empty_rows = FALSE,
    remove_empty_columns = FALSE,
    row_names_gp = gpar(fontsize = 8),
    column_names_gp = gpar(fontsize = 8), 
    row_names_side = "left", pct_side = "right", pct_digits = 1,
    right_annotation = rowAnnotation(row_barplot = anno_oncoprint_barplot(c("1"), border = FALSE, height = unit(4, "cm"), axis_param = list(side = "bottom", labels_rot = 0))), 
    pct_gp = gpar(fontsize = 8), top_annotation = ha, heatmap_legend_param = heatmap_legend_param)
    
draw(oncoprint, heatmap_legend_side = "left", annotation_legend_side = "right", show_heatmap_legend = FALSE)

Fig2e <- grid.grabExpr(draw(oncoprint, heatmap_legend_side = "left", annotation_legend_side = "right", show_heatmap_legend = FALSE))

#Number of patients without genetic annotation (i.e. withouth IGHV)
no_data <- oncoprint_data |> 
  filter(is.na(IGHV.status) & diagnosis.x == "CLL")
