# Load required libraries
library(ggplot2)
library(dplyr)
library(ggrepel)
library(statebins)
library(readxl)
library(RColorBrewer)

df <- read_excel("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/analysis/DDX3X_BTKi/DDX3X_mutations_20241017.xlsx", sheet = "CPS1000")

df_lit <- read_excel("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/analysis/DDX3X_BTKi/DDX3X_mutations_20241017.xlsx", 
    sheet = "literature")

# Mutation data
mutations <- df[,c("position","mutation", "type_adjusted")]
mutations$frequency <- c(rep(1,times=8))

df_lit <- df_lit |>  
  group_by(position) |>  
  mutate(count = n())

mutations_lit <- df_lit[,c("position","mutation", "type_adjusted")]
mutations_lit$frequency <- df_lit$count*(-1)

mutations <- rbind(mutations, mutations_lit)

mutations <- mutations |> 
  mutate(type_adjusted = case_when(
    type_adjusted == "multiple" ~ "Multiple",
    TRUE ~ type_adjusted
  ))

#combine mutations into one label
mutations_combined <- mutations %>%
  group_by(position, frequency) %>%
  summarise(
    mutations = paste(unique(mutation), collapse = ", "),
    .groups = "drop"
  )
#replace type for hotspots with multiple different mutations

# Protein domain data
domains <- data.frame(
  start = c(182, 414),
  end = c(404, 544),
  domain = c("Helicase domain 1", "Helicase domain 2"),
  color = c("#1078af", "#F28E2B")
)

RNA_domains <- data.frame(
  start = c(274, 302, 324, 445, 471, 495),
  end = c(280, 303, 342, 450, 480, 504),
  domain = c("RNA binding"),
  color = c("red")
)

ATP_domains <- data.frame(
  start = c(343, 525),
  end = c(352, 536),
  domain = c("ATP binding"),
  color = c("green")
)

color_data <- rbind(domains,ATP_domains,RNA_domains)

# Protein length
protein_length <- 662

#set colors
mycolors_type <- colorRampPalette(brewer.pal(6, "Set2"))(6)
names(mycolors_type) <- unique(mutations$type_adjusted)

mycolors_domain <- colorRampPalette(brewer.pal(4, "Set3"))(4)
mycolors_domain<- alpha(mycolors_domain, 1)
names(mycolors_domain) <- c("Helicase domain 1", "Helicase domain 2", "ATP binding", "RNA binding")

# Create the plot
plot <- ggplot() +
  # Add mutation lollipops
  geom_segment(data = mutations,
               aes(x = position, xend = position,
                   y = 0, yend = frequency),
               color = "grey50", alpha = 0.5, size = 0.25) +
  
  geom_point(data = mutations,
             aes(x = position, y = frequency, color = type_adjusted), 
             size = 2) +
  
  # Base rectangle representing the gene
  statebins:::geom_rrect(aes(xmin = 0, xmax = protein_length,
                ymin = -0.25, ymax = 0.25),
            fill = "grey95", color = "black", size=0.4) +
  
  # Add protein domains as colored rectangles
  geom_rect(data = domains,
            aes(xmin = start, xmax = end,
                ymin = -0.25, ymax = 0.25, fill = domain),
            color = "black", size=0.25) +
  # add RNA
  geom_rect(data = RNA_domains,
            aes(xmin = start, xmax = end,
                ymin = -0.25, ymax = 0.25,
                fill = domain),
            color = "black", size=0.25) +  
            
  # add ATP
    geom_rect(data = ATP_domains,
            aes(xmin = start, xmax = end,
                ymin = -0.25, ymax = 0.25,
                fill = domain),
            color = "black", size=0.25) +
            
  # Add mutation labels
geom_text_repel(data = mutations_combined,
                aes(x = position, y = frequency,
                    label = mutations),
                size = 3,
                color = "black",
                angle = 90,
                force = 0.1,         # Small repulsion force
                force_pull = 0.1,    # Small pull towards original position
                point.padding = 0.5, # Minimal padding around points
                box.padding = 0.3,   # Padding around label boxes to prevent overlap
                min.segment.length = 0,
                segment.color = "grey80",
                segment.alpha = 0.5,
                segment.size = 0.25,
                nudge_y = ifelse(mutations_combined$frequency < 1, -1, 0.5),
                max.overlaps = Inf,
                max.iter = 3000)+     # More iterations for better positioning
  
  # Add domain labels
  geom_text(data = color_data,
            aes(x = (start + end)/2, y = 0,
                label = "")) +
  
  # Labels
  labs(
    x = "Amino acid position", y = "Number of mutations", color = "Type of mutation", fill= "Domain", title = "DDX3X"
  ) +
  
  # Customize theme
theme_minimal() +
theme(panel.grid = element_blank(),
axis.text = element_text(size = 8, color = "black"),
axis.title.y = element_text(size = 8, hjust = 0.45), axis.title.x = element_text(size = 8),
axis.ticks.x = element_line(color = "black", size = 0.5),  # Add x-axis ticks
axis.ticks.y = element_line(color = "black", size = 0.5),  # Add y-axis ticks
axis.ticks.length = unit(5, "pt"),  # Set the length of tick marks
  legend.position = "right", 
  legend.title = element_text(size = 8, face="bold"), 
  legend.key.size = unit(0.5, 'cm'),
  plot.title = element_text(hjust=0.5, size=8, face="bold")
) +

  # Scale adjustments
  scale_y_continuous(
    expand = c(0, 0), limits = c(-9, 3), breaks = (seq(-6, -1, 1)), labels = c(6,5,4,3,2,1)
  )+
  scale_x_continuous(limits = (c(-20,680)), breaks = c(1,100,200,300,400,500,600,662), expand = (c(0,0))) +geom_segment(aes(x = 1, y = -9, xend = 662, yend = -9), color = "black", size = 0.75)+geom_segment(aes(x = -20, y = -6.015, xend = -20, yend = -0.985), color = "black", size = 0.75)+
  scale_color_manual(values=mycolors_type)+
  scale_fill_manual(values=mycolors_domain)+
guides(fill = guide_legend(override.aes = list(colour = NA)))
  
  
Fig5e <- plot + theme(plot.margin = margin(l=1, r=1, unit = "cm"))
Fig5e

