library(tidyverse)
library(dplyr)
library(ggplot2)
library(patchwork)

#laod raw data
usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

viability_table <- read.csv2("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/viability_table.csv")

IC50_170823 <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/IC50_170823.csv")

#load table with disease entities  
diseases <- usedSamples_all |> 
  arrange(patientID) |> 
  dplyr::select (patientID, diagnosis) 
diseases

# merge the tables
merged_table <- cbind(diseases, viability_table) |> 
  relocate(diagnosis, .before = X10058.F4_1)
merged_table

#transfrom in long data frame
merged_table_long <- merged_table |>
  pivot_longer(cols = c(4:318), names_to = "drug", values_to = "viability")
merged_table_long

#remove last two characters from each string in 'drug' column
merged_table_long$drug <- str_sub(merged_table_long$drug, end = -3)
merged_table_long

#select drugs with concentration A (plates 1 to 4)
groupA <- merged_table_long |> 
  filter(drug == "Cisplatin" | 
  drug == "Imatinib" |
    drug == "A.1210477" |
      drug == "Nutlin.3a" |
        drug == "RO5963" |
          drug == "TW.37" |
            drug == "AZD1208" |
              drug == "Fludarabine" |
                drug == "Methotrexate" |
                  drug == "OTX015" |
                    drug == "Sunitinib" |
                      drug == "Volasertib" |
                        drug == "BGJ398" |
                          drug == "Afatinib" |
                            drug == "Cytarabine" |
                              drug == "IRAK1.4.Inhibitor.I" |
                                drug == "Olaparib" |
                                  drug == "Selisistat" |
                                    drug == "Vismodegib" |
                                      drug == "BML.277" |
                                        drug == "Foretinib" |
                                          drug == "MI.503" |
                                            drug == "Palbociclib" |
                                              drug == "Tozasertib"
  )                      

concentration_A <- rep(c(10, 2, 0.4, 0.08, 0.0016), times = 10944)

df_A <- cbind(groupA, concentration_A) |> 
  rename(concentration = concentration_A)
df_A

#select drugs with concentration B (plate 1 to 4)
groupB <- merged_table_long |> 
  filter(drug == "A.674563" | 
  drug == "BMS.509744" |
    drug == "Dabrafenib" |
      drug == "Ganetespib" |
        drug == "KU.55933" |
          drug == "Motolimod" |
            drug == "PF.3758309" |
              drug == "Ruxolitinib" |
                drug == "SGC.0946" |
                  drug == "AZD6738" |
                    drug == "Cobimetinib" | 
                      drug == "Duvelisib" |
                        drug == "Idelalisib" |
                          drug == "Midostaurin" |
                            drug == "Quizartinib" |
                              drug == "SCH772984" |
                                drug == "Trametinib" |
                                  drug == "AMI.1" |
                                    drug == "Ceritinib" |
                                      drug == "Dasatinib" |
                                        drug == "Ibrutinib" |
                                          drug == "Menin.MLL.Inhibitor" |
                                            drug == "Onalespib" |
                                              drug == "PRT062607" |
                                                drug == "SB.203580" |
                                                  drug == "Tofacitinib" |
                                                    drug == "EPZ.6438" |
                                                      drug == "JNK.IN.8" |
                                                        drug == "MK.2206" |
                                                          drug == "ONO.4059" | 
  drug == "Rapamycin" |
    drug == "10058.F4" |
      drug == "AZD8055" |
        drug == "D4476" |
          drug == "Selinexor" |
            drug == "ZM.336372"
  )                  
  
concentration_B <- rep(c(2, 0.4, 0.08, 0.0016, 0.00032), times = 15960)

df_B <- cbind(groupB, concentration_B)  |> 
  rename(concentration = concentration_B)
df_B

#select drugs with concentration C (plates 1 to 4)
groupC <- merged_table_long |> 
  filter(drug == "Panobinostat" | 
  drug == "Venetoclax" |
    drug == "Doxorubicin"
  ) 
  
concentration_C <- rep(c(0.4, 0.08, 0.0016, 0.00032, 0.000064), times = 912)

df_C <- cbind(groupC, concentration_C)  |> 
  rename(concentration = concentration_C)
df_C

#combine all tables
df_all <- rbind(df_A, df_B, df_C)

#plot CPS1000
plot1 <- df_all |> 
  ggplot(aes(viability)) + 
  geom_density(aes(fill=factor(concentration)), alpha=0.3) + 
  labs(y="Densitiy", x="Viability", title="CPS1000", fill = expression(bold(paste("Concentration (", mu, "M)"))))+
theme_classic()+
scale_fill_brewer(palette = "Blues", direction = 1)+
theme(axis.text.x = element_text(color="black", size=8), axis.text.y = element_text(color="black", size=8), legend.title = element_text(size=8), legend.text=element_text(size=8), axis.line = element_line(size = 0.5), axis.line.x.top = element_line(size = 0.5), plot.title = element_text(hjust=0.5, size=7, face="bold"), axis.title = element_text(size=8), legend.key.size = unit(0.5, 'cm'), plot.margin=margin(r=1,l=1,unit="cm"))+
scale_y_continuous(expand = c(0.02,0))+
scale_x_continuous(limits=c(0,1.25), expand = c(0.02,0))
plot1

#analyze IC50 screen
theme_set(theme_bw())
plot_ic50 <- IC50_170823 |> 
  ggplot(aes(normVal)) +xlim(0,1.25)
plot_ic50 + geom_density(aes(fill=factor(Concentration)), alpha=0.2) + 
    labs(title="Density plot", 
         fill="Concentration")

#create bins         
df <- IC50_170823  |>   
mutate(new_bin = cut(Concentration, breaks=c(0.004, 0.033, 0.156, 0.625, 2.5, 10, 40)))
df_NA <- na.omit(df, new_bin)

#plot IC50 screen
plot2 <- df_NA |> 
  ggplot(aes(normVal)) +
  geom_density(aes(fill=factor(new_bin)), alpha=0.3) + 
  labs(y="Densitiy", x="Viability", title="IC50", fill = expression(bold(paste("Concentration (", mu, "M)"))))+
theme_classic()+
scale_fill_brewer(palette = "Reds", direction = 1, labels = c("0.004 to 0.033", "0.033 to 0.156", "0.156 to 0.625", "0.625 to 2.5", "2.5 to 10", "10 to 40"))+
theme(axis.text.x = element_text(color="black", size=8), axis.text.y = element_text(color="black", size=8), legend.title = element_text(face="bold",size=8), legend.text=element_text(size=8), axis.line = element_line(size = 0.5), axis.line.x.top = element_line(size = 0.5), plot.title = element_text(hjust=0.5, size=7, face="bold"), axis.title = element_text(size=8), legend.key.size = unit(0.5, 'cm'), plot.margin=margin(r=1,l=1,unit="cm"))+
scale_y_continuous(expand = c(0.02,0))+
scale_x_continuous(limits=c(0,1.25), expand = c(0.02,0))
plot2   

Fig2c <- plot1+plot2
Fig2c