library(tidyverse)
library(writexl)
library(readxl)
library(ggpubr)

#load data
usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

viability_table <- read.csv2("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/viability_table.csv")

load("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/patmeta_210324.RData")

#load table with disease entities  
diseases <- usedSamples_all |> 
  arrange(patientID) |> 
  dplyr::select (patientID, diagnosis) 
diseases

# merge the tables
merged_table <- cbind(diseases, viability_table) |> 
  relocate(diagnosis, .before = X10058.F4_1)
merged_table

#transfrom in long data frame
merged_table_long <- merged_table |>
  pivot_longer(cols = c(4:318), names_to = "drug", values_to = "viability")
merged_table_long

#add concentration level and remove last two characters from each string in 'drug' column
merged_table_long$concentration <- rep(seq(1:5), times=nrow(merged_table_long)/5)
merged_table_long$drug <- str_sub(merged_table_long$drug, end = -3)
merged_table_long

#create means
means <- merged_table_long |> 
  group_by(patientID, drug, diagnosis) |> 
  summarize(viab=mean(viability))
means

#focus on main diseases
means_filtered <- means |>
  filter(str_detect(diagnosis, "CLL"))
  
#merge with patMeta
df_merged <- merge(means_filtered, patMeta, by.x="patientID", by.y = "Patient.ID")
  
#select drugs
df_drugs <- df_merged |>
  filter(drug == "Nutlin.3a" | drug == "Fludarabine") |> 
  drop_na(TP53, del17p)
  
#filter TP53 mutated patients
TP53 <- df_drugs |> filter(TP53 == 1)
TP53_list <- unique(TP53$patientID) |> as.data.frame()

#write_xlsx(TP53_list, path = "~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/TP53.xlsx")
TP53_VAF <- read_excel("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/TP53_VAF.xlsx")
TP53_VAF <- TP53_VAF |> 
  drop_na(VAF1) 
TP53_VAF$VAF1 <- as.numeric(TP53_VAF$VAF1)  
TP53_VAF$VAF_total <- rowSums(TP53_VAF[,c("VAF1", "VAF2", "VAF3")], na.rm=TRUE) #some are higher than 1

df_drugs_vaf <- merge(df_drugs, TP53_VAF[,c("PatID", "VAF_total", "multihit", "VAF_above50")], by.x="patientID", by.y="PatID", all = TRUE)

#change NA to 0 for TP53 wt
df_drugs_vaf  <- df_drugs_vaf |> 
  replace_na(list(multihit = "0", VAF1=0)) |> 
  filter(multihit != "NA")
df_drugs_vaf$multihit <- factor(df_drugs_vaf$multihit, levels = unique(df_drugs_vaf$multihit))

#indicate VAF
df_drugs_vaf$VAF_total <- as.numeric(df_drugs_vaf$VAF_total)
df_drugs_vaf$VAF_total[is.na(df_drugs_vaf$VAF_total)] <- 0

#plot graph
mycolors_del17 <- setNames(c("#FC8D62", "grey90"), c(1, 0))

p1 <- df_drugs_vaf |> 
  filter(drug == "Nutlin.3a") |> 
  ggplot(aes(x=TP53, y=viab)) + 
  geom_boxplot(aes(fill=del17p), width = 0.5, position=position_dodge(0.75), outlier.shape = NA, alpha=0.5) + 
  geom_jitter(aes(color=VAF_total, fill=del17p), alpha=0.75, position = position_jitterdodge(jitter.width = 0.1), size=1) + 
#scale_color_manual(values=mycolors, labels=c("unmutated", "mutated")) +
  theme_classic() +
  labs(y = "Mean viability", x="", title = "Nutlin-3a (MDM2)", fill="del17p", color="TP53 total\nvariant\nallele\nfrequency") + 
  stat_compare_means(aes(group = del17p), method = "t.test", label = "p.signif", label.y = 1.05, size=3)+
  theme(
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    legend.position = "right", 
    legend.title=element_text(size=8, face="bold"), 
    legend.text = element_text(size=8), 
    axis.text.x = element_text(color="black", size=8),
    axis.text.y = element_text(color="black", size=8), 
    axis.title.y = element_text(size=8), 
    axis.title.x = element_text(size=8), 
    plot.title = element_text(hjust=0.5, size=8, face="bold"), 
    legend.key.size = unit(0.5, 'cm'), 
    )+
    scale_y_continuous(breaks=seq(0.6,1.0, 0.1), limits=c(0.6,1.05)) +
    scale_x_discrete(labels = c("0" = "TP53 wt", "1" = "TP53 mutated"))+
    scale_shape_manual(values=c(19,17), labels=c("<2", "multihit"))+
    scale_fill_manual(values=mycolors_del17, labels=c("not detected", "present"))+
    scale_color_gradient(low="blue", high="red", guide="colorbar", breaks=c(0,0.25,0.5,0.75,1), labels=c(0,0.25,0.5,0.75,1), limits=(c(0,1)))+
    guides(
      shape = guide_legend(override.aes = list(label = "", fill = NA, linetype = 0)),
      fill = guide_legend(override.aes = list(shape = NA)))
p1

SFig10h <- p1 + theme(plot.margin = margin(t=1, l=1, r=1, unit = "cm"))
SFig10h