library(tidyverse)
library(ggpubr)

#load data
usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

viability_table <- read.csv2("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/viability_table.csv")

load("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/patmeta_210324.RData")

#load table with disease entities  
diseases <- usedSamples_all |> 
  arrange(patientID) |> 
  select (patientID, diagnosis) 
diseases

# merge the tables
merged_table <- cbind(diseases, viability_table) |> 
  relocate(diagnosis, .before = X10058.F4_1)
merged_table

#transfrom in long data frame
merged_table_long <- merged_table |>
  pivot_longer(cols = c(4:318), names_to = "drug", values_to = "viability")
merged_table_long

#add concentration level and remove last two characters from each string in 'drug' column
merged_table_long$concentration <- rep(seq(1:5), times=nrow(merged_table_long)/5)
merged_table_long$drug <- str_sub(merged_table_long$drug, end = -3)
merged_table_long

#focus on main diseases
merged_filtered <- merged_table_long |>
  filter(str_detect(diagnosis, "CLL"))
  
#merge with patMeta
df <- merge(merged_filtered, patMeta, by.x="patientID", by.y = "Patient.ID") 

#select drugs
df_drugs <- df |>
  filter(drug == "Nutlin.3a" | drug == "Fludarabine") |> 
  drop_na(TP53) |> 
  mutate(conc = case_match(concentration, 1 ~ "10", 2 ~ "2", 3 ~ "0.4", 4 ~ "0.08", 5 ~ "0.016"))
  
df_drugs$conc <- factor(df_drugs$conc, levels = c("0.016", "0.08", "0.4", "2", "10"))  

#plot graph
mycolors <- setNames(c("#66C2A5", "grey80"), c(1, 0))

p1 <- df_drugs |> 
  mutate(drug = case_when(drug == "Nutlin.3a" ~ "Nutlin.3a (MDM2)",
                          TRUE ~ drug)) |> 
  ggplot(aes(x=conc, y=viability, color=TP53)) + 
  geom_boxplot(alpha = 1, width = 0.5, position=position_dodge(0.75), outlier.shape = NA) + 
  geom_jitter(alpha = 0.3, position = position_jitterdodge(dodge.width = 0.75, jitter.width = 0.1)) + 
  scale_color_manual(values=mycolors, labels=c("unmutated", "mutated")) +
  theme_bw() +
  labs(y = "Viability", x=bquote("Concentration ("*mu*"M)")) + 
  facet_wrap(.~drug, nrow=2, scales = "free") + 
  stat_compare_means(aes(group = TP53), method = "t.test", label = "p.signif", label.x= 1.25, label.y = 1.05, size=3)+
  theme(strip.text.y = element_text(size = 0), 
        strip.text.x = element_text(size=8),
        axis.text.y = element_text(size =8, color="black"), 
        axis.text.x = element_text(size =8, color="black", angle=45, hjust=1, vjust=1), 
        axis.title = element_text(size =8, color="black"),
        panel.spacing = unit(0.15, "lines"), 
        legend.title = element_text(size=8, face="bold"),
        panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black", linewidth = 1, fill = NA),
        strip.background = element_rect(color = "black", linewidth = 1, fill = "grey90"),        
    plot.title = element_text(hjust=0.5, size=8, face="bold"), 
    legend.key.size = unit(0.5, 'cm'))+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1)) +
    guides(color = guide_legend(override.aes = list(label = ""))) +
    facet_wrap(~drug)
p1

SFig10g <- p1 + theme(plot.margin = margin(t=2, l=1, b=2, unit = "cm"))
SFig10g