library("corrplot")
library(tidyverse)
library(dplyr)
library(gridExtra)
library(patchwork)

usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

viability_table <- read.csv2("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/viability_table.csv")

theme_set(theme_classic() + theme(text = element_text(color="black", size=8), 
axis.line = element_line(size = 0.5)))

#load table with disease entities  
diseases <- usedSamples_all |> 
  arrange(patientID) |> 
  dplyr::select (patientID, diagnosis) 
diseases

# merge the tables
merged_table <- cbind(diseases, viability_table) |> 
  relocate(diagnosis, .before = X10058.F4_1)
merged_table

#transfrom in long data frame
merged_table_long <- merged_table |>
  pivot_longer(cols = c(4:318), names_to = "drug", values_to = "viability")
merged_table_long

#remove last two characters from each string in 'drug' column
merged_table_long$drug <- str_sub(merged_table_long$drug, end = -3)
merged_table_long

#create means
means <- merged_table_long |> 
  group_by(patientID, drug, diagnosis) |> 
  summarize(mean(viability))
means

#filter for CLL
means_cll <- means |>
  filter(str_detect(diagnosis, "CLL")) 

#back to wide format  
df_means <- pivot_wider(means_cll, names_from = drug, values_from = "mean(viability)")
df_means

#selection of drugs: sch_cobi
sch_cobi <- df_means |> dplyr::select(patientID, SCH772984, Cobimetinib)
sch_cobi <- as.data.frame(sch_cobi[, 2:3])

#regression
reg1 <- lm(Cobimetinib ~ SCH772984, sch_cobi)
correlation1 <- cor(sch_cobi$SCH772984, sch_cobi$Cobimetinib)

#plot 
p1 <- sch_cobi |> ggplot(aes(x=SCH772984, y=Cobimetinib)) + geom_point(color="#B2DF8A", alpha=0.5) +
geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) + annotate("text", x=0.8, y=1.2, label = bquote(italic(r) == .(round(correlation1, 2)))) + theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)

#selection of drugs: ibr_cobi
ibr_cobi <- df_means |> dplyr::select(patientID, Ibrutinib, Cobimetinib)
ibr_cobi <- as.data.frame(ibr_cobi[, 2:3])

#regression
reg2 <- lm(Ibrutinib ~ Cobimetinib, ibr_cobi)
correlation2 <- cor(ibr_cobi$Ibrutinib, ibr_cobi$Cobimetinib)

#plot 
p2 <- ibr_cobi |> ggplot(aes(x=Cobimetinib, y=Ibrutinib)) + geom_point(color="#B2DF8A", alpha=0.5) +
geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) + annotate("text", x=0.8, y=1.2, label = bquote(italic(r) == .(round(correlation1, 2)))) + theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)  
  
#selection of drugs:ibr_ide
ibr_ide <- df_means |> dplyr::select(patientID, Ibrutinib, Idelalisib)
ibr_ide <- as.data.frame(ibr_ide[, 2:3])

#regression
reg3 <- lm(Ibrutinib ~ Cobimetinib, ibr_cobi)
correlation3 <- cor(ibr_ide$Ibrutinib, ibr_ide$Idelalisib)

#plot 
p3 <- ibr_ide |> ggplot(aes(x=Idelalisib, y=Ibrutinib)) + geom_point(color="#B2DF8A", alpha=0.5) +
geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) + annotate("text", x=0.8, y=1.2, label = bquote(italic(r) == .(round(correlation1, 2)))) + theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)

#selection of drugs:rapa_ide
rapa_ide <- df_means |> dplyr::select(patientID, Rapamycin, Idelalisib)
rapa_ide <- as.data.frame(rapa_ide[, 2:3])

#regression
reg4 <- lm(Rapamycin ~ Idelalisib, rapa_ide)
correlation4 <- cor(rapa_ide$Rapamycin, rapa_ide$Idelalisib)

#plot 
p4 <- rapa_ide |> ggplot(aes(x=Idelalisib, y=Rapamycin)) + geom_point(color="#B2DF8A", alpha=0.5) +
geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) + annotate("text", x=0.8, y=1.2, label = bquote(italic(r) == .(round(correlation1, 2)))) + theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)

## same for AML
#filter for AML
means_aml <- means |>
  filter(str_detect(diagnosis, "AML")) 

#back to wide format  
df_means_aml <- pivot_wider(means_aml, names_from = drug, values_from = "mean(viability)")
df_means_aml

#selection of drugs: sch_cobi
sch_cobi_aml <- df_means_aml |> dplyr::select(patientID, SCH772984, Cobimetinib)
sch_cobi_aml <- as.data.frame(sch_cobi_aml[, 2:3])

#regression
reg5 <- lm(Cobimetinib ~ SCH772984, sch_cobi_aml)
correlation5 <- cor(sch_cobi_aml$SCH772984, sch_cobi_aml$Cobimetinib)

#plot 
p5 <- sch_cobi_aml |> ggplot(aes(x=SCH772984, y=Cobimetinib)) + geom_point(color="#E31A1C", alpha=0.5) +
geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) + annotate("text", x=0.8, y=1.2, label = bquote(italic(r) == .(round(correlation1, 2)))) + theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)
  
#selection of drugs: ibr_cobi
ibr_cobi_aml <- df_means_aml |> dplyr::select(patientID, Ibrutinib, Cobimetinib)
ibr_cobi_aml <- as.data.frame(ibr_cobi_aml[, 2:3])

#regression
reg6 <- lm(Ibrutinib ~ Cobimetinib, ibr_cobi_aml)
correlation6 <- cor(ibr_cobi_aml$Ibrutinib, ibr_cobi_aml$Cobimetinib)

#plot 
p6 <- ibr_cobi_aml |> ggplot(aes(x=Cobimetinib, y=Ibrutinib)) + geom_point(color="#E31A1C", alpha=0.5) +
geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) + annotate("text", x=0.8, y=1.2, label = bquote(italic(r) == .(round(correlation1, 2)))) + theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)

#selection of drugs:ibr_ide
ibr_ide_aml <- df_means_aml |> dplyr::select(patientID, Ibrutinib, Idelalisib)
ibr_ide_aml <- as.data.frame(ibr_ide_aml[, 2:3])

#regression
reg7 <- lm(Ibrutinib ~ Idelalisib, ibr_ide_aml)
correlation7 <- cor(ibr_ide_aml$Ibrutinib, ibr_ide_aml$Idelalisib)

#plot 
p7 <- ibr_ide_aml |> ggplot(aes(x=Idelalisib, y=Ibrutinib)) + geom_point(color="#E31A1C", alpha=0.5) +
geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) + annotate("text", x=0.8, y=1.2, label = bquote(italic(r) == .(round(correlation1, 2)))) + theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)
p7

#selection of drugs:rapa_ide
rapa_ide_aml <- df_means_aml |> dplyr::select(patientID, Rapamycin, Idelalisib)
rapa_ide_aml <- as.data.frame(rapa_ide_aml[, 2:3])

#regression
reg8 <- lm(Rapamycin ~ Idelalisib, rapa_ide_aml)
correlation8 <- cor(rapa_ide_aml$Rapamycin, rapa_ide_aml$Idelalisib)

#plot 
p8 <- rapa_ide_aml |> ggplot(aes(x=Idelalisib, y=Rapamycin)) + geom_point(color="#E31A1C", alpha=0.5) +
geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) + annotate("text", x=0.8, y=1.2, label = bquote(italic(r) == .(round(correlation1, 2)))) + theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)
p8

#first plot
p1|p3|p2|p4 
p5|p7|p6|p8 

p1+p5 + theme(plot.margin = unit(c(0,30,0,0), "pt")) +
p3+p7 + theme(plot.margin = unit(c(0,30,0,0), "pt")) +
p2+p6 + theme(plot.margin = unit(c(0,30,0,0), "pt")) +
p4+p8 + plot_layout(ncol = 8) + theme(plot.margin = margin(t=1, unit = "cm"))

#new plot with legends
mycolors <- setNames(c("#E31A1C", "#B2DF8A"), c("AML", "CLL"))

#sch_cobi
sch_cobi <-cbind(sch_cobi,Diagnosis = rep("CLL", nrow(sch_cobi)), corr = rep(round(correlation1,2), nrow(sch_cobi)))

sch_cobi_aml <-cbind(sch_cobi_aml,Diagnosis = rep("AML", nrow(sch_cobi_aml)), corr = rep(round(correlation5,2), nrow(sch_cobi_aml)))

sch_cobi_comb <- rbind(sch_cobi, sch_cobi_aml)
sch_cobi_comb$corr <- as.character(sch_cobi_comb$corr)

p9 <- sch_cobi_comb |> ggplot(aes(x=SCH772984, y=Cobimetinib)) + 
  geom_point(aes(color=Diagnosis), alpha=0.5) +
  geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) +
  geom_text(aes(label=paste0("italic(r) == ", corr)), x=0.8, y=1.2, size=3, 
  check_overlap = TRUE, parse = TRUE)+
  facet_wrap(~Diagnosis)+
  theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)+ 
  theme(
  axis.text = element_text(color="black", size=8), 
  legend.title = element_text(size=8, face="bold"), 
  legend.text=element_text(size=8), 
  axis.line = element_line(size = 0.5), 
  axis.title = element_text(size=8),
  legend.key.size = unit(0.5, 'cm'),
  strip.background = element_blank(),
  strip.text.x = element_blank(), 
  panel.spacing = unit(1, "lines")
  )+
  scale_color_manual(values = mycolors)+
  xlab("SCH772984 (ERK)")+
  ylab("Cobimetinib (MEK)")
p9

#ibr_ide 
ibr_ide <-cbind(ibr_ide,Diagnosis = rep("CLL", nrow(ibr_ide)), corr = rep(round(correlation3,2), nrow(ibr_ide)))

ibr_ide_aml <-cbind(ibr_ide_aml,Diagnosis = rep("AML", nrow(ibr_ide_aml)), corr = rep(round(correlation7,2), nrow(ibr_ide_aml)))

ibr_ide_comb <- rbind(ibr_ide, ibr_ide_aml)
ibr_ide_comb$corr <- as.character(ibr_ide_comb$corr)

p10 <- ibr_ide_comb |> ggplot(aes(x=Ibrutinib, y=Idelalisib)) + 
  geom_point(aes(color=Diagnosis), alpha=0.5) +
  geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) +
  geom_text(aes(label=paste0("italic(r) == ", corr)), x=0.8, y=1.2, size=3, 
  check_overlap = TRUE, parse = TRUE)+  facet_wrap(~Diagnosis)+
  theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)+ 
  theme(
  axis.text = element_text(color="black", size=8), 
  legend.title = element_text(size=8, face="bold"), 
  legend.text=element_text(size=8), 
  axis.line = element_line(size = 0.5), 
  axis.title = element_text(size=8),
  legend.key.size = unit(0.5, 'cm'),
  strip.background = element_blank(),
  strip.text.x = element_blank(), 
  panel.spacing = unit(1, "lines")
  )+
  scale_color_manual(values = mycolors)+
  xlab("Ibrutinib (BTK)")+
  ylab("Idelalisib (PI3K)")
p10

#ibr_cobi 
ibr_cobi <-cbind(ibr_cobi,Diagnosis = rep("CLL", nrow(ibr_cobi)), corr = rep(round(correlation2,2), nrow(ibr_cobi)))

ibr_cobi_aml <-cbind(ibr_cobi_aml,Diagnosis = rep("AML", nrow(ibr_cobi_aml)), corr = rep(round(correlation6,2), nrow(ibr_cobi_aml)))

ibr_cobi_comb <- rbind(ibr_cobi, ibr_cobi_aml)
ibr_cobi_comb$corr <- as.character(ibr_cobi_comb$corr)

p11 <- ibr_cobi_comb |> ggplot(aes(x=Ibrutinib, y=Cobimetinib)) + 
  geom_point(aes(color=Diagnosis), alpha=0.5) +
  geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) +
  geom_text(aes(label=paste0("italic(r) == ", corr)), x=0.8, y=1.2, size=3, 
  check_overlap = TRUE, parse = TRUE)+
  facet_wrap(~Diagnosis)+
  theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)+ 
  theme(
  axis.text = element_text(color="black", size=8), 
  legend.title = element_text(size=8, face="bold"), 
  legend.text=element_text(size=8), 
  axis.line = element_line(size = 0.5), 
  axis.title = element_text(size=8),
  legend.key.size = unit(0.5, 'cm'),
  strip.background = element_blank(),
  strip.text.x = element_blank(), 
  panel.spacing = unit(1, "lines")
  )+
  scale_color_manual(values = mycolors)+
  xlab("Ibrutinib (BTK)")+
  ylab("Cobimetinib (MEK)")
p11

#rapa_ide 
rapa_ide <-cbind(rapa_ide,Diagnosis = rep("CLL", nrow(rapa_ide)), corr = rep(round(correlation4,2), nrow(rapa_ide)))

rapa_ide_aml <-cbind(rapa_ide_aml,Diagnosis = rep("AML", nrow(rapa_ide_aml)), corr = rep(round(correlation8,2), nrow(rapa_ide_aml)))

rapa_ide_comb <- rbind(rapa_ide, rapa_ide_aml)
rapa_ide_comb$corr <- as.character(rapa_ide_comb$corr)

p12 <- rapa_ide_comb |> ggplot(aes(x=Rapamycin, y=Idelalisib)) + 
  geom_point(aes(color=Diagnosis), alpha=0.5) +
  geom_smooth(
    method = "lm",    # Use linear model
    se = TRUE,        # Show standard error (confidence interval)
    level = 0.95,     # 95% confidence interval
    color = "black",    # Color of the regression line
    fill = "lightgrey" # Color of the confidence interval
  ) +
  geom_text(aes(label=paste0("italic(r) == ", corr)), x=0.8, y=1.2, size=3, 
  check_overlap = TRUE, parse = TRUE)+
  facet_wrap(~Diagnosis)+
  theme_classic() + xlim(0.4,1.2) + ylim(0.4,1.2)+ 
  theme(
  axis.text = element_text(color="black", size=8), 
  legend.title = element_text(size=8, face="bold"), 
  legend.text=element_text(size=8), 
  axis.line = element_line(size = 0.5), 
  axis.title = element_text(size=8),
  legend.key.size = unit(0.5, 'cm'),
  strip.background = element_blank(),
  strip.text.x = element_blank(), 
  panel.spacing = unit(1, "lines")
  )+
  scale_color_manual(values = mycolors)+
  xlab("Rapamycin (mTOR)")+
  ylab("Idelalisib (PI3K)")
p12

#new plot
Fig4b <- p9+p10+p11+p12+plot_layout(ncol=4, guides =
'collect') & theme(legend.position='right', legend.title= element_text(size=8, face="bold"), plot.margin = margin(t=0.25, l=0.5, b=0.25, r=0.5, unit = "cm")) & guides(
    color = guide_legend(ncol = 1),
    fill = guide_legend(ncol = 1),
    shape = guide_legend(ncol = 1),
    linetype = guide_legend(ncol = 1)
  )
Fig4b