library(tidyverse)
library(plotrix)

#load data
usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

viability_table <- read.csv2("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/viability_table.csv")

#load table with disease entities  
diseases <- usedSamples_all |> 
  arrange(patientID) |> 
  select (patientID, diagnosis) 
diseases

# merge the tables
merged_table <- cbind(diseases, viability_table) |> 
  relocate(diagnosis, .before = X10058.F4_1)
merged_table

#transfrom in long data frame
merged_table_long <- merged_table |>
  pivot_longer(cols = c(4:318), names_to = "drug", values_to = "viability")
merged_table_long

#focus on main diseases
merged_filtered <- merged_table_long
#|>filter(str_detect(diagnosis, "CLL") | str_detect(diagnosis, "MCL") |         str_detect(diagnosis, "AML") | str_detect(diagnosis, "B-ALL") | str_detect(diagnosis, "T-ALL") | str_detect(diagnosis, "B-PLL")  | str_detect(diagnosis, "T-PLL"))
merged_filtered 


#remove last two characters from each string in 'drug' column
merged_filtered<- merged_filtered |> 
  mutate(drug_sub = str_sub(merged_filtered$drug, end = -3)) |> 
    filter(diagnosis != "")

#select venetoclax and diseases
merged_filtered <- merged_filtered |> 
    filter(drug_sub == "Venetoclax") |> 
    filter(diagnosis == "AML" | diagnosis == "B-ALL" | diagnosis == "Sezary" | diagnosis == "CLL" | diagnosis == "T-ALL" | diagnosis == "MCL") |> 
    mutate(drug = fct_recode(drug, "0.00064" = "Venetoclax_1",
"0.0032" = "Venetoclax_2", "0.016" = "Venetoclax_3", "0.08" = "Venetoclax_4", "0.4" = "Venetoclax_5"))

#change order
merged_filtered$diagnosis <- as.factor(merged_filtered$diagnosis)
merged_filtered$diagnosis <- factor(merged_filtered$diagnosis, levels = c("CLL","B-ALL", "MCL", "AML", "T-ALL", "Sezary"))

#set colors
mycolors <- setNames(c("#1F78B4", "#B2DF8A", "#33A02C", "grey", "#E31A1C", "#FB9A99", "#FF7F00", "#CAB2D6"), c("CLL", "B-PLL", "T-PLL", "other", "AML", "T-ALL", "B-ALL", "MCL"))

#plot for venetoclax
plot <- merged_filtered |>
    ggplot(aes(x=rev(factor(drug)), y=viability, group=diagnosis, color=diagnosis)) +
    geom_boxplot(aes(group=drug), alpha = 0.5, outlier.shape = NA)+
    geom_jitter(aes(group=diagnosis), size=1, alpha = 0.5)+
    labs(title="Venetoclax",x="concentration [uM]", y = "viability")+
    scale_y_continuous(breaks=seq(0,1.0, 0.2), limits=c(0,1.1))+
    theme_bw()+
    stat_summary(fun = median, geom = "path", mapping = aes(group = -1))+ 
    facet_wrap(~diagnosis, ncol = 6) +
    scale_color_manual(values=mycolors)+
    labs(y="Viability", x=bquote("Concentration ("*mu*"M)"))+
theme(legend.position = "none", axis.text.x = element_text(angle = 45, hjust=1, color="black", size=8), panel.grid = element_line(colour = "white"), axis.text.y = element_text(color="black", size=8), 
#axis.line = element_line(size = 0.5), 
axis.title.y = element_text(size=8), axis.title.x = element_text(size=8), plot.title = element_text(hjust=0.5, size=8), strip.text = element_text(size = 8), plot.margin =  margin(l = 0.5, r = 1, unit = "cm"))

Fig3f <- plot
Fig3f

