library(tidyverse)
library(ggplot2)
library(patchwork)

usedSamples_all <- read.csv("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/usedSamples_all.csv", sep=";")

viability_table <- read.csv2("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/viability_table.csv")

load("~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/raw data/patmeta_210324.RData")

#load table with disease entities  
diseases <- usedSamples_all |> 
  arrange(patientID) |> 
  dplyr::select (patientID, diagnosis) 
diseases

# merge the tables
merged_table <- cbind(diseases, viability_table) |> 
  relocate(diagnosis, .before = X10058.F4_1)
merged_table

#transfrom in long data frame
merged_table_long <- merged_table |>
  pivot_longer(cols = c(4:318), names_to = "drug", values_to = "viability")
merged_table_long

#remove last two characters from each string in 'drug' column
merged_table_long$drug <- str_sub(merged_table_long$drug, end = -3)
merged_table_long

#change order according to mean viability  
merged_table_long_order <- group_by(merged_table_long, drug) |> 
  summarise(mean = mean(viability), n = n()) |> 
  arrange (-mean)
  
merged_table_long$drug <- factor(merged_table_long$drug, levels = merged_table_long_order$drug)  

#exclude entities with small n
merged_filtered <- merged_table_long |>
  filter(str_detect(diagnosis, "CLL") | str_detect(diagnosis, "MCL") |         str_detect(diagnosis, "AML") | str_detect(diagnosis, "B-ALL") |            str_detect(diagnosis, "T-ALL") | str_detect(diagnosis, "B-PLL")  |         str_detect(diagnosis, "T-PLL"))
merged_filtered

#merge with patMeta for IGHV status and create "other" group
ighv <- patMeta[, c(1, 9)]

merged_filtered_IGHV <- merged_filtered |> 
  merge(ighv, by.x = "patientID", by.y= "Patient.ID", all.x = TRUE) |>     
  mutate(IGHV = case_when(IGHV.status == "U" ~ "U-CLL",
                        IGHV.status == "M" ~ "M-CLL",
                        TRUE ~ diagnosis)) |> 
                        filter(IGHV != "CLL")
                        
unique(merged_filtered_IGHV$IGHV)                        
  
#create facets
facets_filterd <- merged_filtered |> 
  ggplot(aes(viability, drug)) + 
  xlim(0,1.25)
facets_filterd + geom_point (alpha = 1/10, colour = "red") + facet_grid(. ~ diagnosis)

#add box plots to facets
facets_filterd <- merged_filtered |> 
  ggplot(aes(viability, drug)) + 
  xlim(0,1)
facets_filterd + geom_boxplot(alpha = 1/10, colour = "red") + facet_grid(. ~ diagnosis) + theme(axis.text.x = element_text(angle = 90))
 
levels(merged_filtered$diagnosis)
merged_filtered$diagnosis <- factor(merged_filtered$diagnosis, levels = unique(merged_filtered$diagnosis))  

# order according to median viability for each disease
#set colors
mycolors <- setNames(c("#1F78B4", "#B2DF8A", "#33A02C", "#A6CEE3", "grey", "#E31A1C", "#FB9A99", "#FF7F00", "#CAB2D6"), c("MCL", "U-CLL", "M-CLL", "T-PLL", "other", "AML", "T-ALL", "B-ALL", "B-PLL")) 

#M-CLL - ranking
mcll_order <- filter(merged_filtered_IGHV, IGHV == "M-CLL") |> 
  group_by(drug) |> 
  summarise(median = median(viability), n = n()) |> 
  arrange(desc(median)) |> 
  pull(drug)
  
mcll_df <- merged_filtered_IGHV |> 
  filter(IGHV == "M-CLL")

mcll_df$drug <- factor(mcll_df$drug, levels = mcll_order)  

#M-CLL plot
mcll <- mcll_df |> 
  ggplot(aes(x=viability, y=drug, fill=IGHV), color="black") + 
  geom_boxplot(alpha = 0.75)+
  xlim(0,1.25)+
  theme_bw() +
  labs(y="", x="Mean viability", title="M-CLL")+
  theme(axis.text = element_text(color="black", angle = 0, size=8), axis.title = element_text(size=8), plot.title = element_text(size=8, hjust=0.5, face="bold"),
  legend.position = "none",
  panel.border = element_rect(color = "black", linewidth = 1, fill = NA))+
scale_fill_manual(values=mycolors)+
scale_color_manual(values=mycolors)

#U-CLL - ranking
ucll_order <- filter(merged_filtered_IGHV, IGHV == "U-CLL") |> 
  group_by(drug) |> 
  summarise(median = median(viability), n = n()) |> 
  arrange(desc(median)) |> 
  pull(drug)
  
ucll_df <- merged_filtered_IGHV |> 
  filter(IGHV == "U-CLL")

ucll_df$drug <- factor(ucll_df$drug, levels = ucll_order)  

#U-CLL plot
ucll <- ucll_df |> 
  ggplot(aes(x=viability, y=drug, fill=IGHV), color="black") + 
  geom_boxplot(alpha = 0.75)+
  xlim(0,1.25)+
  theme_bw() +
  labs(y="", x="Mean viability", title="U-CLL")+
  theme(axis.text = element_text(color="black", angle = 0, size=8), axis.title = element_text(size=8), plot.title = element_text(size=8, hjust=0.5, face="bold"),
  legend.position = "none",
  panel.border = element_rect(color = "black", linewidth = 1, fill = NA))+
scale_fill_manual(values=mycolors)+
scale_color_manual(values=mycolors)

#AML - ranking
aml_order <- filter(merged_filtered_IGHV, IGHV == "AML") |> 
  group_by(drug) |> 
  summarise(median = median(viability), n = n()) |> 
  arrange(desc(median)) |> 
  pull(drug)
  
aml_df <- merged_filtered_IGHV |> 
  filter(IGHV == "AML")

aml_df$drug <- factor(aml_df$drug, levels = aml_order)  

#AML plot
aml <- aml_df |> 
  ggplot(aes(x=viability, y=drug, fill=IGHV), color="black") + 
  geom_boxplot(alpha = 0.75)+
  xlim(0,1.25)+
  theme_bw() +
  labs(y="", x="Mean viability", title="AML")+
  theme(axis.text = element_text(color="black", angle = 0, size=8), axis.title = element_text(size=8), plot.title = element_text(size=8, hjust=0.5, face="bold"),
  legend.position = "none",
  panel.border = element_rect(color = "black", linewidth = 1, fill = NA))+
scale_fill_manual(values=mycolors)+
scale_color_manual(values=mycolors)

#T-ALL - ranking
tall_order <- filter(merged_filtered_IGHV, IGHV == "T-ALL") |> 
  group_by(drug) |> 
  summarise(median = median(viability), n = n()) |> 
  arrange(desc(median)) |> 
  pull(drug)
  
tall_df <- merged_filtered_IGHV |> 
  filter(IGHV == "T-ALL")

tall_df$drug <- factor(tall_df$drug, levels = tall_order)  

#T-ALL plot
tall <- tall_df |> 
  ggplot(aes(x=viability, y=drug, fill=IGHV), color="black") + 
  geom_boxplot(alpha = 0.75)+
  xlim(0,1.25)+
  theme_bw() +
  labs(y="", x="Mean viability", title="T-ALL")+
  theme(axis.text = element_text(color="black", angle = 0, size=8), axis.title = element_text(size=8), plot.title = element_text(size=8, hjust=0.5, face="bold"),
  legend.position = "none",
  panel.border = element_rect(color = "black", linewidth = 1, fill = NA))+
scale_fill_manual(values=mycolors)+
scale_color_manual(values=mycolors)

#B-ALL - ranking
ball_order <- filter(merged_filtered_IGHV, IGHV == "B-ALL") |> 
  group_by(drug) |> 
  summarise(median = median(viability), n = n()) |> 
  arrange(desc(median)) |> 
  pull(drug)
  
ball_df <- merged_filtered_IGHV |> 
  filter(IGHV == "B-ALL")

ball_df$drug <- factor(ball_df$drug, levels = ball_order)  

#B-ALL plot
ball <- ball_df |> 
  ggplot(aes(x=viability, y=drug, fill=IGHV), color="black") + 
  geom_boxplot(alpha = 0.75)+
  xlim(0,1.25)+
  theme_bw() +
  labs(y="", x="Mean viability", title="B-ALL")+
  theme(axis.text = element_text(color="black", angle = 0, size=8), axis.title = element_text(size=8), plot.title = element_text(size=8, hjust=0.5, face="bold"),
  legend.position = "none",
  panel.border = element_rect(color = "black", linewidth = 1, fill = NA))+
scale_fill_manual(values=mycolors)+
scale_color_manual(values=mycolors)

#B-PLL - ranking
bpll_order <- filter(merged_filtered_IGHV, IGHV == "B-PLL") |> 
  group_by(drug) |> 
  summarise(median = median(viability), n = n()) |> 
  arrange(desc(median)) |> 
  pull(drug)
  
bpll_df <- merged_filtered_IGHV |> 
  filter(IGHV == "B-PLL")
  
bpll_df$drug <- factor(bpll_df$drug, levels = bpll_order)  

#B-PLL plot
bpll <- bpll_df |> 
  ggplot(aes(x=viability, y=drug, fill=IGHV), color="black") + 
  geom_boxplot(alpha = 0.75)+
  xlim(0,1.25)+
  theme_bw() +
  labs(y="", x="Mean viability", title="B-PLL")+
  theme(axis.text = element_text(color="black", angle = 0, size=8), axis.title = element_text(size=8), plot.title = element_text(size=8, hjust=0.5, face="bold"),
  legend.position = "none",
  panel.border = element_rect(color = "black", linewidth = 1, fill = NA))+
scale_fill_manual(values=mycolors)+
scale_color_manual(values=mycolors)

#T-PLL - ranking
tpll_order <- filter(merged_filtered_IGHV, IGHV == "T-PLL") |> 
  group_by(drug) |> 
  summarise(median = median(viability), n = n()) |> 
  arrange(desc(median)) |> 
  pull(drug)
  
tpll_df <- merged_filtered_IGHV |> 
  filter(IGHV == "T-PLL")
  
tpll_df$drug <- factor(tpll_df$drug, levels = tpll_order)  

#T-PLL plot
tpll <- tpll_df |> 
  ggplot(aes(x=viability, y=drug, fill=IGHV), color="black") + 
  geom_boxplot(alpha = 0.75)+
  xlim(0,1.25)+
  theme_bw() +
  labs(y="", x="Mean viability", title="T-PLL")+
  theme(axis.text = element_text(color="black", angle = 0, size=8), axis.title = element_text(size=8), plot.title = element_text(size=8, hjust=0.5, face="bold"),
  legend.position = "none",
  panel.border = element_rect(color = "black", linewidth = 1, fill = NA))+
scale_fill_manual(values=mycolors)+
scale_color_manual(values=mycolors)

#MCL - ranking
mcl_order <- filter(merged_filtered_IGHV, IGHV == "MCL") |> 
  group_by(drug) |> 
  summarise(median = median(viability), n = n()) |> 
  arrange(desc(median)) |> 
  pull(drug)
  
mcl_df <- merged_filtered_IGHV |> 
  filter(IGHV == "MCL")
  
mcl_df$drug <- factor(mcl_df$drug, levels = mcl_order)  

#MCL plot
mcl <- mcl_df |> 
  ggplot(aes(x=viability, y=drug, fill=IGHV), color="black") + 
  geom_boxplot(alpha = 0.75)+
  xlim(0,1.25)+
  theme_bw() +
  labs(y="", x="Mean viability", title="MCL")+
  theme(axis.text = element_text(color="black", angle = 0, size=8), axis.title = element_text(size=8), plot.title = element_text(size=8, hjust=0.5, face="bold"),
  legend.position = "none",
  panel.border = element_rect(color = "black", linewidth = 1, fill = NA))+
scale_fill_manual(values=mycolors)+
scale_color_manual(values=mycolors)




#plot all together
library(cowplot)
library(patchwork)
library(ggpubr)

SFig6 <- plot_grid(aml, ball, tall, NULL, NULL, ncol = 5, nrow = 1)

SFig6 <- plot_grid(SFig6, NULL, ncol = 1, nrow =2, rel_heights = c(0.4, 0.6)) & theme(plot.margin = margin(t=1, l=1, r=1, unit = "cm"))

ggsave(file="~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/figures/SFig.6/SFig6.pdf", plot=SFig6, width=42, height=59.4, units = "cm")

ggsave(file="~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/figures/SFig.6/SFig6.png", plot=SFig6, width=42, height=59.4, units = "cm", dpi = 300)

SFig7 <- plot_grid(bpll, mcll, mcl, ucll, tpll, ncol = 5, nrow = 1)

SFig7 <- plot_grid(SFig7, NULL, ncol = 1, nrow =2, rel_heights = c(0.4, 0.6)) & theme(plot.margin = margin(t=1, l=1, r=1, unit = "cm"))

ggsave(file="~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/figures/SFig.7/SFig7.pdf", plot=SFig7, width=42, height=59.4, units = "cm")

ggsave(file="~/Dropbox/Medizin/Forschung/Aktuelle Forschungsprojekte/CLL CPS1000/figures/SFig.7/SFig7.png", plot=SFig7, width=42, height=59.4, units = "cm", dpi = 300)

